services:
    render_client:
      container_name: render_client
      build:
            context: .
            dockerfile: './docker/client/Dockerfile'
      restart: 'always'
      volumes:
            - './:/app'
      # command: sleep infinity
      # deploy:
      #   resources:
      #     reservations:
      #       devices:
      #         - driver: nvidia
      #           count: all # alternatively, use `count: all` for all GPUs
      #           capabilities: [gpu]
